import { productTypeLabels, stageLabels } from "../data/trustOptions";
import type { TrustFinding, TrustPageSection, TrustProfile, TrustScore, TrustTask } from "../models/trust";

function bulletList(items: string[]) {
  return items.length ? items.map((item) => `- ${item}`).join("\n") : "- Not listed yet";
}

function findingList(findings: TrustFinding[], priority: "high" | "medium" | "low") {
  const filtered = findings.filter((finding) => finding.priority === priority);
  if (filtered.length === 0) return "- None found by the current rules";

  return filtered
    .map((finding) => `- **${finding.title}** - ${finding.summary}\n  - Suggested fix: ${finding.suggestedFix[0]}`)
    .join("\n");
}

function taskList(tasks: TrustTask[]) {
  if (tasks.length === 0) return "- No developer tasks generated";

  return tasks
    .map(
      (task) =>
        `- **${task.id}** ${task.title} - ${task.priority} priority, ${task.estimatedEffort} effort, owner: ${task.suggestedOwner}`
    )
    .join("\n");
}

function trustPageDraft(sections: TrustPageSection[]) {
  return sections.map((section) => `### ${section.title}\n_Status: ${section.status}_\n\n${section.content}`).join("\n\n");
}

export function generateMarkdownReport(
  profile: TrustProfile,
  score: TrustScore,
  findings: TrustFinding[],
  tasks: TrustTask[],
  sections: TrustPageSection[]
) {
  const categoryLines = [
    `- Privacy Basics: ${score.categories.privacyBasics}%`,
    `- Security Signals: ${score.categories.securitySignals}%`,
    `- Data Handling: ${score.categories.dataHandling}%`,
    `- Vendor Transparency: ${score.categories.vendorTransparency}%`,
    `- Customer Readiness: ${score.categories.customerReadiness}%`,
    ...(score.categories.aiTransparency !== undefined ? [`- AI Transparency: ${score.categories.aiTransparency}%`] : [])
  ].join("\n");

  return `# ShipTrust Report - ${profile.productName}

## Trust Score
${score.total}/100 - ${score.level}

## Product Profile
- Product type: ${productTypeLabels[profile.productType]}
- Stage: ${stageLabels[profile.stage]}
- Description: ${profile.description}
- Target customers: ${profile.targetCustomers || "Not listed yet"}
- Data collected:
${bulletList(profile.collectedData)}
- Infrastructure:
${bulletList(profile.infrastructure)}
- Third-party providers:
${bulletList(profile.thirdParties)}

## Category Breakdown
${categoryLines}

## High Priority Trust Gaps
${findingList(findings, "high")}

## Medium Priority Trust Gaps
${findingList(findings, "medium")}

## Low Priority Trust Gaps
${findingList(findings, "low")}

## Suggested Developer Tasks
${taskList(tasks)}

## Trust Page Draft
${trustPageDraft(sections)}

## Recommended Next Steps
- Publish or review the highest-priority missing trust signals first.
- Add the generated trust page draft to a public page when it is accurate.
- Link trust basics from your footer, signup flow or sales materials.
- Re-run ShipTrust after making the suggested fixes.

---

Generated by ShipTrust.
`;
}

export async function copyTextToClipboard(text: string) {
  if (navigator.clipboard?.writeText) {
    await navigator.clipboard.writeText(text);
  }
}

export function downloadMarkdown(filename: string, markdown: string) {
  const blob = new Blob([markdown], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  link.remove();
  URL.revokeObjectURL(url);
}
